# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np 
arr = np.loadtxt('minutes_n_ingredients.csv', dtype=str, delimiter = ',')
arr_new = np.array(arr[1:,:], np.int32)
a = np.array(arr[1:5], np.int32)
print(a)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
stolb_1 = a[:,1]
stolb_2 = a[:,2]
print(f'Cтолбец 1 среднее значение:{np.mean(stolb_1)}, минимум:{np.mean(stolb_1)}, максимум:{np.max(stolb_1)}, медиана:{np.median(stolb_1)}')
print(f'Cтолбец 2 среднее значение:{np.mean(stolb_2)}, минимум:{np.mean(stolb_2)}, максимум:{np.max(stolb_2)}, медиана:{np.median(stolb_2)}')

Cтолбец 1 среднее значение:32.0, минимум:32.0, максимум:60, медиана:25.0
Cтолбец 2 среднее значение:9.8, минимум:9.8, максимум:16, медиана:7.0


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [19]:
arr[np.random.randint(low=0,high=len(arr[:,0]),size=10)]

array([['92096', '200', '11'],
       ['470106', '60', '20'],
       ['67332', '720', '13'],
       ['13295', '42', '10'],
       ['433242', '15', '8'],
       ['38542', '20', '7'],
       ['173173', '12', '12'],
       ['125754', '10', '5'],
       ['382417', '90', '11'],
       ['344772', '30', '7']], dtype='<U13')

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [52]:
b= np.array(arr[1:,2], np.int32)
arr_new[np.where((b==5)|(b<5))]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [88]:
kolvo_ing = arr_new[:,2]
print(len(arr_new[kolvo_ing < np.mean(kolvo_ing)])*100 / len(arr_new))

58.802


6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [4]:
prod_recepie = arr_new[:, 1]
q_3 = np.percentile(prod_recepie, 75)
np.where(prod_recepie > q_3, q_3, prod_recepie) 

array([60., 25., 10., ..., 65.,  5., 65.])

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [94]:
arr_new[:,1] = np.array(np.where(prod_recepie == 0, 1, prod_recepie))
print(arr_new)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [119]:
v, vxod = np.unique(kolvo_ing, return_counts = True)
c = np.arange(1,42)
elements_v = np.isin(c,v)
print(*c[(elements_v == False)])

36 38 40 41


9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины длzя всего датасета.

In [121]:
np.max(arr_new[:,2] / arr_new[:,1])

24.0

10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [145]:
ind = np.argsort(arr_new[:,1])
ingrid = arr_new[ind][:100:-1][:,2][:100]
np.mean(ingrid)

6.61

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [155]:
prostoy_recepie = np.where((prod_recepie < 20) & (kolvo_ing < 5), 1,0)
np.column_stack((arr_new, prostoy_recepie))

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [161]:
prostoy_recepie.sum() / len(prostoy_recepie) * 100

5.093

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [35]:
groups = np.where(prod_recepie < 10, 0, np.where(prod_recepie < 20, 1, 2))
array = np.column_stack((groups, arr_new))
shirina = max(np.unique(groups, return_counts=True)[1])
m = np.full([3, shirina, 2], np.nan)

In [36]:
prost_recipe,standart_recipe,dlinn_recipe = array[groups == 0], array[groups == 1], array[groups == 2]

In [39]:
m[0] [: prost_recipe.shape[0]] = prost_recipe[:,2:]
m[1] [: standart_recipe.shape[0]] = standart_recipe[:,2:]
m[2] [: dlinn_recipe.shape[0]] = dlinn_recipe[:,2:]
m

array([[[  5.,   6.],
        [  7.,   9.],
        [  5.,   3.],
        ...,
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan]],

       [[ 10.,   6.],
        [ 18.,   9.],
        [ 15.,   5.],
        ...,
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan]],

       [[ 60.,  16.],
        [ 25.,   7.],
        [ 60.,  14.],
        ...,
        [ 85.,  15.],
        [ 65.,  15.],
        [140.,  14.]]])

In [38]:
print(m.ndim, m.shape)

3 (3, 79751, 2)


13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.